urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dashboard/', views.dash, name='dash'),
    path('helpline/', views.help, name='help'),
    path('news/', views.news, name='news'),
]

models.py
from django.db import models

# Create your models here.

views.py
import mpld3
from django.shortcuts import render
from django.http import HttpResponse

from bokeh.plotting import figure, output_file, show
from bokeh.embed import components
# Bokeh Libraries
from bokeh.io import output_notebook
from bokeh.plotting import figure, show
output_notebook()
# import plotly.express as px

import tweepy
from textblob import TextBlob

# import necessary libraries
import pandas as pd
import numpy as np
# from wordcloud import WordCloud, STOPWORDS
import re
import matplotlib.pyplot as plt
import seaborn as sns

# Retrieving tweets from twitter
consumer_key = 'CbbklaZ4A7iOmpo9ZfsYFuWxU'
consumer_key_secret = 'RwR6OI6WVJag84B1NIk6OPCd2vv2EwFiBKpU7exePcPIDxWUZc'
access_token = '1282233149594800128-kNp1ZvypJxDLjT4A0kOKW2QjZnnBMh'
access_token_secret = 'MjvpVkdhg5MdROIMFSBDsJt0dH6a0jQFHEFKFQp2LAArb'
auth = tweepy.OAuthHandler(consumer_key, consumer_key_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

public_tweets = api.search('COVID-19', lang="en", count=100)
for tweet in public_tweets:

    print(tweet.created_at)
    print(tweet.text)
    analysis = TextBlob(tweet.text)
    print(analysis.sentiment)
    if analysis.sentiment[0] > 0:
        print("Positive")
    elif analysis.sentiment[0] < 0:
        print("Negative")
    else:
        print("Neutral")

# stopwords = set(STOPWORDS)

plt.style.use('fivethirtyeight')
i = 1
for tweet in public_tweets[0:5]:
    print(str(i) + ') ' + tweet.text + '\n')
    i = i + 1
df = pd.DataFrame([tweet.text for tweet in public_tweets], columns=['Tweets'])
df['Date'] = pd.DataFrame([tweet.created_at for tweet in public_tweets], columns=['Date'])
for i in range(df.shape[0]):
    df['Tweets'][i] = ' '.join(
        re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\S+)|(#[A-Za-z0-9]+)", " ", df['Tweets'][i]).split()).lower()


def getSubjectivity(text):
    return TextBlob(text).sentiment.subjectivity


def getPolarity(text):
    return TextBlob(text).sentiment.polarity


df['Subjectivity'] = df['Tweets'].apply(getSubjectivity)
df['Polarity'] = df['Tweets'].apply(getPolarity)

#Sentiment Analysis
def getAnalysis(score):
  if score<0:
    return 'Negative'
  elif score==0:
    return 'Neutral'
  else:
    return 'Positive'

df['Analysis']=df['Polarity'].apply(getAnalysis)


#print all the positive tweets
j=1
sortedDF=df.sort_values(by=['Polarity'])
for i in range(0,sortedDF.shape[0]):
  if(sortedDF['Analysis'][i]=='Positive'):
    print(str(j)+') '+sortedDF['Tweets'][i])
    print()
    j=j+1


def home(request):
    return render(request, 'home/index.html')
    


def about(request):
    return render(request, 'home/page4.html')
 
def news(request):
    return render(request, 'home/page1.html')

def help(request):
    return render(request, 'home/page2.html')

# def (request):
#     return render(request, 'home/.html')


# def index(request):
#     x = [1, 3, 5, 7, 9, 11, 13]
#     y = [1, 2, 3, 4, 5, 6, 7]
#     title = 'y = f(x)'

#     plot = figure(title=title,
#                   x_axis_label='X-Axis',
#                   y_axis_label='Y-Axis',
#                   plot_width=400,
#                   plot_height=400)

#     plot.line(x, y)


#     script, div = components(plot)

#     return render(request, 'home/web_home.html', {'script': script, 'div': div, })


def dash(request):
    fig = plt.figure(figsize=(10, 6))
    for i1 in range(0, df.shape[0]):
        plt.scatter(df['Polarity'][i1], df['Subjectivity'][i1], color='Blue')
    plt.title('Sentiment Analysis of COVID-19')
    plt.xlabel('Polarity')
    plt.ylabel('Subjectivity')
    # plt.show()
    sgraph = mpld3.fig_to_html(fig)

    # # percentage of positive comments
    # ptweets = df[df.Analysis == 'Positive']
    # ptweets = ptweets['Tweets']
    # round((ptweets.shape[0] / df.shape[0]) * 100, 1)

    # # percentage of negative comments
    # ntweets = df[df.Analysis == 'Negative']
    # ntweets = ntweets['Tweets']
    # round((ntweets.shape[0] / df.shape[0]) * 100, 1)

    # # percentage of neutral comments
    # neutweets = df[df.Analysis == 'Neutral']
    # neutweets = neutweets['Tweets']
    # round((neutweets.shape[0] / df.shape[0]) * 100, 1)

    # # Number of tweets per hour
    # tweets_per_hour = plt.figure(1, figsize=(10, 6))
    plt.hist(df["Date"], bins=24, color='orange');
    plt.xlabel('Hours', size=15)
    plt.ylabel('No. of Tweets', size=15)
    plt.title('No. of Tweets per Hour', size=15)

   # tgraph = mpld3.fig_to_html(tweets_per_hour)

    # seaborn

    sea_me = plt.figure(figsize=(15, 8))
    sns.distplot(df['Polarity'], bins=30, color='green')
    plt.title('Sentiment Distribution', size=25)
    plt.xlabel('Polarity', size=20)
    plt.ylabel('Frequency', size=20)
    sbgraph = mpld3.fig_to_html(sea_me)


    
    # create figure 
    p = figure(plot_width = 1200, plot_height = 550,x_axis_label='Polarity',y_axis_label='Subjectivity',title='Sentiment Analysis') 
    p.title.text_font_size = '20pt'
    p.xaxis.axis_label_text_font_size = "20pt"
    p.yaxis.axis_label_text_font_size = "20pt"
        
    # add a line renderer 
    p.hexbin(df['Polarity'],df['Subjectivity'], line_width = 5, color = "green",size=0.2, hover_color="pink", hover_alpha=0.8) 
        
    # Show the plot
    show(p)
    script1, div1 = components(p)

    #create figure
    p2 = figure(plot_width=1200, plot_height=550,x_axis_label='Date',title='Sentiment Analysis')
    p2.title.text_font_size = '20pt'
    p2.xaxis.axis_label_text_font_size = "20pt"

    # add a circle renderer with a size, color, and alpha
    p2.circle(df['Date'], df['Polarity'], size=15, color="navy", alpha=0.5)
    p2.circle(df['Date'],df['Subjectivity'],size=15, color="orange", alpha=0.5)

    # show the results
    script2, div2 = components(p2)


    p3 = figure(plot_width = 600, plot_height = 600, 
    title = 'Scatter Plot between polarity and subjectivity',
    x_axis_label = 'Polarity', y_axis_label = 'Subjectivity')
    p3.circle(df['Polarity'], df['Subjectivity'])
    # output_notebook()
    script3, div3 = components(p3)


    date=df['Date']
    polarity=df['Polarity']
    p4 = figure(x_axis_label='Tweets per hour', y_axis_label='Polarity')
    p4.line(date,polarity)
    p4.circle(date,polarity, fill_color='black', size=20)
    # output_notebook()

    script4, div4 = components(p4)
    
    bok = [  [script3, div3], [script4, div4] ]

    hor = [ [script1, div1], [script2, div2] ]




    content = {'fig': sbgraph,'hor': hor, 'bok': bok  ,'title':'Dashboard'}

    return render(request, 'home/dash.html', content) # page3

templates/home/dash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, shrink-to-fit=no, maximum-scale=1.0, user-scalable=no">
    <title>Dashboard</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home/web.css' %}">
    <link rel="shortcut icon" href="{% static 'images/icon.png' %}" type="image/x-icon">
    
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-2.1.1.min.js"></script>
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.0.min.js"></script>
    <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-2.1.1.min.css">
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-2.1.1.min.css" rel="stylesheet" type="text/css">

</head>

<body>


    <h1>Dashboard for visualizations</h1>
    <div class=container>
        {% for eh in hor %}
        {% for eins in eh %}
            <div class="hor">
            {{eins|safe}}
            </div>
        {% endfor %}
         {% endfor %}
    <div class = "bes">
    {% for eg in bok %}
    {% for einside in eg %}
        <div class="ver">
        {{einside|safe}}
        </div>
    {% endfor %}

    {% endfor %}
</div>
    </div>
    <div class="gr">
    {{ fig |safe}}
    </div>
    <script>
        window.watsonAssistantChatOptions = {
            integrationID: "346b7245-5170-4e27-936c-75b13bb28b13", // The ID of this integration.
            region: "eu-gb", // The region your integration is hosted in.
            serviceInstanceID: "a3c3ca8d-994e-4023-a4e0-14f7fa1cce7e", // The ID of your service instance.
            onLoad: function (instance) { instance.render(); }
        };
        setTimeout(function () {
            const t = document.createElement('script');
            t.src = "https://web-chat.global.assistant.watson.appdomain.cloud/loadWatsonAssistantChat.js";
            document.head.appendChild(t);
        });
    </script>

</body>

</html>

templates/home/index.html
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.12.4, https://mobirise.com -->
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.12.4, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'images/icon.png' %}" type="image/x-icon">
  <meta name="description" content="">
  
  <!-- "{% static 'home/' %}" -->


  <title>Home</title>
  <link rel="stylesheet" href="{% static 'home/assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/assets/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/assets/theme/css/style.css' %}">
  <link rel="preload" as="style" href="{% static 'home/assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'home/assets/mobirise/css/mbr-additional.css' %}" type="text/css">
  
  
  
</head>
<body>
  <section class="header3 cid-s5mxReTmZ1 mbr-parallax-background" id="header3-c">

    

    <div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(35, 35, 35);">
    </div>

    <div class="container">
        <div class="media-container-row">
            <div class="mbr-figure" style="width: 100%;">
                <img src="{% static 'home/assets/images/bird-800x675.png' %}" alt="Mobirise" title="">
            </div>

            <div class="media-content">
                <h1 class="mbr-section-title mbr-white pb-3 mbr-fonts-style display-1"><strong><em>Welcome to ShinjoZone!</em></strong></h1>
                
                <div class="mbr-section-text mbr-white pb-3 ">
                    <p class="mbr-text mbr-fonts-style display-5">Looking for Covid-19 Sentiment Analysis?<br>You are at the right place!</p>
                </div>
                <!-- <div class="mbr-section-btn"><a class="btn btn-md btn-primary display-4" href="https://mobirise.co">LEARN MORE</a></div> -->
            </div>
        </div>
    </div>

</section>

<section class="engine"><a href="https://mobirise.info/p">site templates free download</a></section><section class="features2 cid-s5mxZXbmx7 mbr-parallax-background" id="features2-d">

    

    <div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(239, 239, 239);">
    </div>
    
    <div class="container">
        <div class="media-container-row">
            <div class="card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-wrapper">
                    <div class="card-img">
                        <img src="{% static 'home/assets/images/images-36-676x283.jpg' %}" alt="Mobirise" title="">
                    </div>
                    <div class="card-box">
                        <h4 class="card-title pb-3 mbr-fonts-style display-5"><strong><em>ShinjoZone</em></strong></h4>
                        <p class="mbr-text mbr-fonts-style display-7"><strong>It's a Webapp where you can get to know about people's sentiments towards the Covid-19 pandemic.Tweets are analysed to draw interactive dashboards which informs us about the Coronavirus outbreak in our country.</strong></p>
                    </div>
                </div>
            </div>

            <div class="card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-wrapper">
                    <div class="card-img">
                        <img src="{% static 'home/assets/images/images-21-676x380.jpg' %}" alt="Mobirise" title="">
                    </div>
                    <div class="card-box ">
                        <h4 class="card-title pb-3 mbr-fonts-style display-5"><strong><em>News</em></strong></h4>
                        <p class="mbr-text mbr-fonts-style display-7"><strong>Want to get more information about the Coronavirus Pandemic? Click here to get the latest news about it</strong>. <a href="{% url 'home:news' %}" class="text-primary"><strong>Click here to view more</strong></a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-wrapper">
                    <div class="card-img">
                        <a href="{% url 'home:about' %}"><img src="{% static 'home/assets/images/images-37-357x280.jpeg' %}" alt="Mobirise" title=""></a>
                    </div>
                    <div class="card-box">
                        <h4 class="card-title pb-3 mbr-fonts-style display-5"><strong>About Us</strong></h4>
                        <p class="mbr-text mbr-fonts-style display-4"><strong>Want to know more about us?&nbsp;</strong></p>
                    </div>
                </div>
            </div>

            
        </div>
    </div>
</section>

<section class="features2 cid-s5my8qq67E mbr-parallax-background" id="features2-e">

    

    <div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(239, 239, 239);">
    </div>
    
    <div class="container">
        <div class="media-container-row">
            <div class="card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-wrapper">
                    <div class="card-img">
                        <img src="{% static 'home/assets/images/images-34-676x451.jpeg' %}" alt="Mobirise" title="">
                    </div>
                    <div class="card-box">
                        <h4 class="card-title pb-3 mbr-fonts-style display-5"><strong>Helpline</strong></h4>
                        <p class="mbr-text mbr-fonts-style display-7"><strong>You are not Alone! Let's Fight this together!&nbsp;<a href="{% url 'home:help' %}"><b>Click here to view more</b></a></strong>
                        </p>
                    </div>
                </div>
            </div>

            <div class="card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-wrapper">
                    <div class="card-img">
                        <img src="{% static 'home/assets/images/images-2-216x233.png' %}" alt="Mobirise" title="">
                    </div>
                    <div class="card-box ">
                        <h4 class="card-title pb-3 mbr-fonts-style display-5"><strong>DashBoard</strong></h4>
                        <p class="mbr-text mbr-fonts-style display-7"><strong>
                            Want to see the sentiments of covid19 tweets as graphical user interface? This is the right place you are looking for! </strong> <a href="{% url 'home:dash' %}" ><strong>Click here to view more</strong></a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-wrapper">
                    <div class="card-img">
                        <img src="{% static 'home/assets/images/images-32-533x576.jpeg' %}" alt="Mobirise" title="">
                    </div>
                    <div class="card-box">
                        <h4 class="card-title pb-3 mbr-fonts-style display-5"><strong>ShinjoBot</strong><br><br></h4>
                        <p class="mbr-text mbr-fonts-style display-7"><strong>Worried about getting the right info on covid-19. Ask me anything you need and am here to help you</strong>.</p>
                    </div>
                </div>
            </div>

            
        </div>
    </div>
</section>


  <script src="{% static 'home/assets/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'home/assets/popper/popper.min.js' %}"></script>
  <script src="{% static 'home/assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'home/assets/tether/tether.min.js' %}"></script>
  <script src="{% static 'home/assets/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'home/assets/parallax/jarallax.min.js' %}"></script>
  <script src="{% static 'home/assets/theme/js/script.js' %}"></script>
  <script>
    window.watsonAssistantChatOptions = {
        integrationID: "346b7245-5170-4e27-936c-75b13bb28b13", // The ID of this integration.
        region: "eu-gb", // The region your integration is hosted in.
        serviceInstanceID: "a3c3ca8d-994e-4023-a4e0-14f7fa1cce7e", // The ID of your service instance.
        onLoad: function (instance) { instance.render(); }
    };
    setTimeout(function () {
        const t = document.createElement('script');
        t.src = "https://web-chat.global.assistant.watson.appdomain.cloud/loadWatsonAssistantChat.js";
        document.head.appendChild(t);
    });
</script>
  
</body>
</html>

templates/home/page1.html
<!DOCTYPE html>
<html  >
<head>
    {% load static %}
  <!-- Site made with Mobirise Website Builder v4.12.4, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.12.4, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'images/icon.png' %}" type="image/x-icon">
  <meta name="description" content="Website Builder Description">
  
  
  <title>News</title>
  <link rel="stylesheet" href="{% static 'home/assets/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'home/assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/assets/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/assets/socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'home/assets/theme/css/style.css' %}">
  <link rel="preload" as="style" href="{% static 'home/assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'home/assets/mobirise/css/mbr-additional.css' %}" type="text/css">
  
  
  
</head>
<body>
  <section class="features11 cid-s5mJAavrh3 mbr-parallax-background" id="features11-j">

    

    <div class="mbr-overlay" style="opacity: 0.7; background-color: rgb(255, 255, 255);">
    </div>

    <div class="container">   
        <div class="col-md-12">
            <div class="media-container-row">
                <div class="mbr-figure m-auto" style="width: 50%;">
                    <img src="{% static 'home/assets/images/img-20200721-wa0074-2-400x300.png' %}" alt="Mobirise" title="">
                </div>
                <div class=" align-left aside-content">
                    <h2 class="mbr-title pt-2 mbr-fonts-style display-1"><strong><em>OverAll Stats</em></strong></h2>
                    <div class="mbr-section-text">
                        <p class="mbr-text mb-5 pt-3 mbr-light mbr-fonts-style display-5"><strong>Stay updated about the CoronaVirus Stats all over the World and especially in India.</strong><br></p>
                    </div>

                    <div class="block-content">
                        <div class="card p-3 pr-3">
                            <div class="media">
                                <div class=" align-self-center card-img pb-3">
                                    <span class="mbr-iconfont mbri-extension" style="color: rgb(35, 35, 35); fill: rgb(35, 35, 35);"></span>
                                </div>     
                                <div class="media-body">
                                    <h4 class="card-title mbr-fonts-style display-2"><strong>All Over the World</strong></h4>
                                </div>
                            </div>                

                            <div class="card-box">
                                <p class="block-text mbr-fonts-style display-5"><strong><em>Total Confirmed Cases: 15M &nbsp;<br>Total Active Cases: 5567432<br>Total Recovered Cases: 8.30M <br>Total Deaths</em>: 611k</strong><br></p>
                            </div>
                        </div>

                        <div class="card p-3 pr-3">
                            <div class="media">
                                <div class="align-self-center card-img pb-3">
                                    <span class="mbr-iconfont mbri-drag-n-drop2" style="color: rgb(35, 35, 35); fill: rgb(35, 35, 35);"></span>
                                </div>     
                                <div class="media-body">
                                    <h4 class="card-title mbr-fonts-style display-2"><strong>In India</strong></h4>
                                </div>
                            </div>                

                            <div class="card-box">
                                <p class="block-text mbr-fonts-style display-5"><strong>Total Confirmed Cases: 1250000<br>Total Active Cases:500720<br>Total Recovered Cases:737308<br>Total Deaths:28560</strong></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>          
</section>

<section class="engine"><a href="https://mobirise.info/i">free web creation software</a></section><section class="features8 cid-s5mZoI5vbI mbr-parallax-background" id="features8-m">

    

    <div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(35, 35, 35);">
    </div>

    <div class="container">
        <div class="media-container-row">

            <div class="card  col-12 col-md-6 col-lg-4">
                <div class="card-img">
                    <span class="mbr-iconfont socicon-blizzard socicon"></span>
                </div>
                <div class="card-box align-center">
                    <h4 class="card-title mbr-fonts-style display-7">Boris Johnson</h4>
                    <p class="mbr-text mbr-fonts-style display-7">Prime Minister Boris Johnson on Monday dampened prospects of an effective coronavirus vaccine by the end of this year, as initial results of a widely-followed human trial at the University of Oxford were due to be released later in the day.</p>
                    <div class="mbr-section-btn text-center"><a href="https://www.hindustantimes.com/world-news/british-pm-boris-johnson-dampens-hopes-of-covid-19-vaccine-this-year/story-8t75dI7qpks9XBIr5HCjdL.html" class="btn btn-secondary display-4" target="_blank">
                            More
                        </a></div>
                </div>
            </div>

            <div class="card  col-12 col-md-6 col-lg-4">
                <div class="card-img">
                    <span class="mbri-touch mbr-iconfont"></span>
                </div>
                <div class="card-box align-center">
                    <h4 class="card-title mbr-fonts-style display-7">CoronaVirus Vaccine</h4>
                    <p class="mbr-text mbr-fonts-style display-7">Prime Minister Boris Johnson on Monday dampened prospects of an effective coronavirus vaccine by the end of this year, as initial results of a widely-followed human trial at the University of Oxford were due to be released later in the day.</p>
                    <div class="mbr-section-btn text-center"><a href="https://www.hindustantimes.com/world-news/oxford-s-covid-19-vaccine-candidate-s-initial-results-show-it-is-safe/story-SO1USJvXyCi3hVWp0h4g4L.html" class="btn btn-secondary display-4" target="_blank">
                            More
                        </a></div>
                </div>
            </div>

            <div class="card  col-12 col-md-6 col-lg-4">
                <div class="card-img">
                    <span class="mbri-responsive mbr-iconfont"></span>
                </div>
                <div class="card-box align-center">
                    <h4 class="card-title mbr-fonts-style display-7">Covid-19 India Taly</h4>
                    <p class="mbr-text mbr-fonts-style display-7">India’s tally of the coronavirus disease (Covid-19) mounted to 1,118,043 after 40,425 new cases, in a record single-day spike, were reported in the last 24 hours, with more than 200,000 infections.<br>
<br></p>
                    <div class="mbr-section-btn text-center"><a href="https://www.hindustantimes.com/india-news/india-s-covid-19-tally-goes-past-1-11-million-recoveries-cross-7-lakh/story-iG90WLqHCUMaEbIss7N9NM.html" class="btn btn-secondary display-4" target="_blank">
                            More
                        </a></div>
                </div>
            </div>

            
        </div>
    </div>
</section>


  <script src="{% static 'home/assets/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'home/assets/popper/popper.min.js' %}"></script>
  <script src="{% static 'home/assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'home/assets/tether/tether.min.js' %}"></script>
  <script src="{% static 'home/assets/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'home/assets/parallax/jarallax.min.js' %}"></script>
  <script src="{% static 'home/assets/theme/js/script.js' %}"></script>
  <script>
    window.watsonAssistantChatOptions = {
        integrationID: "346b7245-5170-4e27-936c-75b13bb28b13", // The ID of this integration.
        region: "eu-gb", // The region your integration is hosted in.
        serviceInstanceID: "a3c3ca8d-994e-4023-a4e0-14f7fa1cce7e", // The ID of your service instance.
        onLoad: function (instance) { instance.render(); }
    };
    setTimeout(function () {
        const t = document.createElement('script');
        t.src = "https://web-chat.global.assistant.watson.appdomain.cloud/loadWatsonAssistantChat.js";
        document.head.appendChild(t);
    });
</script>
  
</body>
</html>